baseURL = "https://iamcarl.vercel.app/"
languageCode = "en-us"
title = "Carl Angelo Nievarez"
theme = "cactus"
copyright = "Carl Angelo Nievarez" # cactus will use title if copyright is not set
disqusShortname = "Carl Angelo Nievarez" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "You're a curious person."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://iamcarl.vercel.app/projects" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "aice09/iamcarl"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/aice09"
  [[params.social]]
    name = "youtube"
    link = "https://www.youtube.com/@aice0927"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/AiceCarl"
  [[params.social]]
    name = "facebook"
    link = "https://www.facebook.com/aice0927/"
  [[params.social]]
    name = "instagram"
    link = "https://www.instagram.com/aice0927/"
  [[params.social]]
    name = "stack-overflow"
    link = "https://stackoverflow.com/users/7299528/carl-angelo-nievarez?tab=profile"
  [[params.social]]
    name = "dev"
    link = "https://dev.to/aice09" 
  [[params.social]]
    name = "discord"
    link = "https://discord.gg/8p9JdUeZUx" 
  [[params.social]]
    name = "medium"
    link = "https://discord.gg/8p9JdUeZUx" 
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/aice0927/"
  [[params.social]]
    name = "gitlab"
    link = "https://gitlab.com/aice0927"
  [[params.social]]
    name = "bitbucket"
    link = "https://bitbucket.org/aice0927/"    
  [[params.social]]
    name = "email"
    link = "nievarez.carlangelo@gmail.com"  # no need for "mailto:" in the head